name: Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
          - os: macos-15
          - os: macos-26
          - os: ubuntu-latest
          - os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@v1

      - name: Show Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Test
        run: swift test
