name: Windows Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: Swift ${{ matrix.swift }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Swift 6.2
          - swift: "6.2"
            os: windows-2025
          - swift: "6.2"
            os: windows-2022

          # Swift 6.1
          - swift: "6.1"
            os: windows-2025
          - swift: "6.1"
            os: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}

      - name: Show Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Test
        run: swift test
